version: "3.4"

services:
  app:
    image: petmanagerapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PNPM_HOME: "/pnpm"
      PATH: "$PNPM_HOME:$PATH"
    ports:
      - 3000:3003
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
