services:
  postgres:
    ports:
      - "${DB_PORT}:${DB_PORT}"
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 5s
      timeout: 60s
      retries: 5
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PNPM_HOME: "/pnpm"
      PATH: "$PNPM_HOME:$PATH"
      PORT: "${PORT}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_PORT: "${DB_PORT}"
      POSTGRES_HOST: "postgres"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  pgdata:
